name: 'Glo Parse Card Links'
description: 'GitHub Action to parse links to Glo Boards cards'
branding:
  color: 'blue'
  icon: 'link'
outputs:
  boards:
    description: Stringified array of boards with list of cards
runs:
  using: 'node12'
  main: 'lib/main.js'
