on: pull_request

name: Tests
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: Check out repo
      uses: actions/checkout@master

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
